@PMT!
select 
, PMT.EXT_REQ_NUMBER, PMT.INVOICE_ENTER_DATE, PMT.BUDGET_NAME, PMT.FIN_ORG_NAME, PMT.GRBS_NAME, PMT.GRBS_CODE, PMT.PAYER_NAME, PMT.SU_CODE_ENTERED, PMT.PA, PMT.ft_s_name, PMT.TOFK_CODE, PMT.OKPO_CODE, PMT.lim_date, PMT.BC_DOC_REG_NUMBER, PMT.cheque_lost_flag, PMT.CHEQUE_RCVR_POSITION, PMT.CHEQUE_RECEIVER_NAME, PMT.cheque_rcvr_doc_type, PMT.cheque_rcvr_doc_num, PMT.cheque_rcvr_doc_issuer, PMT.cheque_rcvr_doc_date, PMT.MANAGER_POSITION, PMT.MANAGER, PMT.accounter_name, PMT.accounter_position, PMT.accounter_date, PMT.DOC_REG_NUMBER, PMT.DOC_REG_DATE, PMT.EXECUTOR_POSITION, PMT.EXECUTOR, PMT.EXECUTOR_PHONE, PMT.label_access, PMT.PAYER_BANK_ACCOUNT, PMT.PAYER_BANK_BIK, PMT.PAYER_BANK_KS, PMT.PAYER_INN, PMT.PAYER_BANK_NAME, PMT.PAYER_KPP, PMT.RECEIVER_BANK_ACCOUNT, PMT.RECEIVER_BANK_BIK, PMT.RECEIVER_BANK_KS, PMT.RECEIVER_BANK_NAME, PMT.RECEIVER_INN, PMT.RECEIVER_KPP, PMT.DR_LAST_UPDATE_date
from
xxt_bc_zkr_doc_v PMT where doc_guid= 

@PMT1!
select 
, PMT1.line_number, PMT1.cheque_line_amount, PMT1.CHEQUE_NUM, PMT1.CHEQUE_SERIES, PMT1.CHEQUE_DATE, PMT1.CHEQUE_USAGE_TERM, PMT1.SYMBOL_KASS_PLAN, PMT1.VERSION, PMT1.CREATION_DATE, PMT1.LAST_UPDATE_DATE
from
XXT_BC_CHEQUES_vers_V PMT1
left Join xxt_bc_zkr_doc_v PMT on PMT1.INVOICE_ID = PMT.INVOICE_ID where PMT.doc_guid= 

@PMT1_TOTAL!
select 
, PMT1_TOTAL.invoice_amount
from
xxt_bc_zkr_doc_v PMT1_TOTAL
left Join xxt_bc_zkr_doc_v PMT on PMT1_TOTAL.invoice_id=pmt.invoice_id where PMT.doc_guid= 

@LINES!
select 
, LINES.DISTRIBUTION_LINE_NUMBER, LINES.FUND_SOURCE_NAME, LINES.BCC_CODE_entered, LINES.AMOUNT, LINES.PAYMENT_PURPOSE, LINES.SUBSIDY_TARGET_CODE, LINES.DESCRIPTION
from
XXT_BC_ZKR_LINES_V LINES
left Join xxt_bc_zkr_doc_v PMT on LINES.INVOICE_ID = PMT.INVOICE_ID where PMT.doc_guid= 

