@DOC_HEADERS!
select 
, DOC_HEADERS.DOC_NUMBER, DOC_HEADERS.DOC_DATE, DOC_HEADERS.UOM, DOC_HEADERS.SU_NAME, DOC_HEADERS.REG_NUMBER, DOC_HEADERS.REG_DATE, DOC_HEADERS.BANK_BIK, DOC_HEADERS.BUSINESS_STATUS_NAME, DOC_HEADERS.TRANSFER_STATUS, DOC_HEADERS.TRANSFER_STATUS_NAME, DOC_HEADERS.APPROVAL_STATUS, DOC_HEADERS.APPROVAL_STATUS_NAME, DOC_HEADERS.DOC_SOURCE, DOC_HEADERS.DOC_SOURCE_NAME, DOC_HEADERS.EXECUTOR_POSITION, DOC_HEADERS.EXECUTOR_NAME, DOC_HEADERS.EXECUTOR_DATE, DOC_HEADERS.EXECUTOR_PHONE, DOC_HEADERS.FK_MANAGER_POSITION, DOC_HEADERS.FK_MANAGER_NAME, DOC_HEADERS.FK_EXECUTOR_POSITION, DOC_HEADERS.FK_EXECUTOR_NAME, DOC_HEADERS.FK_EXECUTOR_PHONE, DOC_HEADERS.MANAGER_POSITION, DOC_HEADERS.MANAGER_NAME, DOC_HEADERS.ATTRIBUTE1, DOC_HEADERS.BUDGET_ACCOUNT
from
XXT_RV_DOC_HEADERS_V DOC_HEADERS where doc_guid= 

@DOC_LINES1!
select 
, DOC_LINES1.LINE_NUMBER1, DOC_LINES1.DOC_NAME, DOC_LINES1.DOC_NUMBER, DOC_LINES1.DOC_DATE, DOC_LINES1.RECEIVER_NAME, DOC_LINES1.RECEIVER_INN, DOC_LINES1.RECEIVER_KPP, DOC_LINES1.OKATO_CODE1, DOC_LINES1.BCC, DOC_LINES1.SUBSIDY_TARGET_CODE, DOC_LINES1.SUBSIDY_TARGET_CODE_R, DOC_LINES1.AMOUNT, DOC_LINES1.expence_right, DOC_LINES1.PAYMENT_PURPOSE, DOC_LINES1.DESCRIPTION, DOC_LINES1.CREATION_DATE, DOC_LINES1.LAST_UPDATE_DATE, DOC_LINES1.ATTRIBUTE1, DOC_LINES1.FUND_SOURCE, DOC_LINES1.ATTRIBUTE3, DOC_LINES1.ATTRIBUTE4, DOC_LINES1.ATTRIBUTE5, DOC_LINES1.ATTRIBUTE6, DOC_LINES1.ATTRIBUTE7, DOC_LINES1.ATTRIBUTE8, DOC_LINES1.ATTRIBUTE9, DOC_LINES1.FK_OPER, DOC_LINES1.BANK_ACCOUNT_NUM_PAYER, DOC_LINES1.BANK_ACCOUNT_NUM_RECEIVER, DOC_LINES1.PA_CODE_UUK, DOC_LINES1.LAST_YEAR_FLAG
from
XXT_RV_DOC_LINES_V DOC_LINES1
left Join XXT_RV_DOC_HEADERS_V DOC_HEADERS on DOC_LINES1.HEADER_ID = DOC_HEADERS.HEADER_ID where DOC_HEADERS.doc_guid= 

@DOC_LINES2!
select 
, DOC_LINES2.LINE_NUMBER1, DOC_LINES2.RECEIVER_NAME, DOC_LINES2.RECEIVER_INN, DOC_LINES2.RECEIVER_KPP, DOC_LINES2.OKATO_CODE1, DOC_LINES2.BCC, DOC_LINES2.SUBSIDY_TARGET_CODE, DOC_LINES2.SUBSIDY_TARGET_CODE_R, DOC_LINES2.AMOUNT, DOC_LINES2.fund_source_code, DOC_LINES2.KAZN_FLAG, DOC_LINES2.PAYMENT_PURPOSE, DOC_LINES2.CREATION_DATE, DOC_LINES2.LAST_UPDATE_DATE, DOC_LINES2.ATTRIBUTE1, DOC_LINES2.FUND_SOURCE, DOC_LINES2.FK_OPER, DOC_LINES2.BANK_ACCOUNT_NUM_PAYER, DOC_LINES2.BANK_ACCOUNT_NUM_RECEIVER, DOC_LINES2.PA_CODE_UUK
from
XXT_RV_DOC_LINES_V DOC_LINES2
left Join XXT_RV_DOC_LINES_V DOC_LINES1 on DOC_LINES2.HEADER_ID = DOC_LINES1.HEADER_ID AND&#10;DOC_LINES2.LINE_NUMBER1 = DOC_LINES1.LINE_NUMBER1 where DOC_LINES1.doc_guid= 

